# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    echo Testing connectivity to SonarQube server...
    curl -v https://codeanalysis.silicus.com/
  displayName: 'Test SonarQube Server Connectivity'
  timeoutInMinutes: 10
  
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sq_connect_asa' # Replace with your SonarQube service connection name
    scannerMode: 'MSBuild'
    projectKey: 'GenAI_project' # Replace with your project key
    projectName: 'GenAI_project' # Replace with your project name
    
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'