name: 'code-review'
on:
  pull_request:
permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gvasilei/AutoReviewer@0.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          exclude_files: '*.json, *.md, *.yml, *.razor'
